export const CUSTOMER_GET_ERRORS = "CUSTOMER_GET_ERRORS";
export const CUSTOMER_SET_LOADING = "CUSTOMER_SET_LOADING";
export const CUSTOMER_GET_USER = "CUSTOMER_GET_USER";
export const CUSTOMER_GET_PROFILE = "CUSTOMER_GET_PROFILE";
export const CUSTOMER_SET_MESSAGE = "CUSTOMER_SET_MESSAGE";

export const CUSTOMER_LOGOUT = "CUSTOMER_LOGOUT";
