export const ADMIN_GET_ERRORS = "ADMIN_GET_ERRORS";
export const ADMIN_SET_LOADING = "ADMIN_SET_LOADING";
export const ADMIN_GET_USER = "ADMIN_GET_USER";
export const ADMIN_GET_PROFILE = "ADMIN_GET_PROFILE";
export const ADMIN_SET_MESSAGE = "ADMIN_SET_MESSAGE";

export const ADMIN_GET_TRANSACTION_HISTORY = "ADMIN_GET_TRANSACTION_HISTORY";


export const ADMIN_LOGOUT = "ADMIN_LOGOUT";